const timelineElements = [
  {
    id: 1,
    title: "High School Diploma",
    location: "Bietigheim-Bissingen, Baden-Württemberg",
    description:
      "Vocational School Center Bietigheim, Technical High School - Focus on Computer Science",
    buttonText: "Details",
    date: "2019-2022",
    icon: "school",
    color: "yellow",
    tech: ["HTML", "CSS", "PHP", "C#"],
  },
  {
    id: 2,
    title: "Summer Job",
    location: "Stuttgart, Baden-Württemberg",
    description: "Etas GmbH",
    buttonText: "Details",
    date: "2024",
    icon: "school",
    color: "yellow",
    tech: ["-"],
  },
  {
    id: 3,
    title: "Software Engineering",
    location: "Esslingen, Baden-Württemberg",
    description: "Studying",
    buttonText: "Details",
    date: "2022-2023",
    icon: "school",
    color: "orange",
    tech: ["C"],
  },
  {
    id: 4,
    title: "Working Student Job",
    location: "Böblingen, Baden-Württemberg",
    description: "Transitioned to a front-end development role",
    buttonText: "Details",
    date: "2024",
    icon: "work",
    color: "red",
    tech: ["TypeScript", "Angular", "Spring Boot", "Figma"],
  },
  {
    id: 5,
    title: "Media Informatics",
    location: "Stuttgart, Baden-Württemberg",
    description: "Studying",
    buttonText: "Details",
    date: "2023-present",
    icon: "school",
    color: "orange",
    tech: ["JavaScript", "React", "HTML", "CSS", "Java", "TypeScript"],
  },
];

export default timelineElements.reverse();
